# Generated by Django 5.1.4 on 2025-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lib_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_id', models.CharField(max_length=50)),
                ('passcode', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=300)),
                ('DOB', models.CharField(max_length=300)),
                ('POR', models.CharField(max_length=300)),
                ('lib_Admin_no', models.CharField(max_length=300)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
