# Generated by Django 5.1.4 on 2025-01-30 14:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_lib_admin_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lib_admin',
            name='ldap_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ldap_id',
        ),
        migrations.AlterField(
            model_name='lib_admin',
            name='DOB',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lib_admin',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lib_admin',
            name='POR',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lib_admin',
            name='lib_Admin_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lib_admin',
            name='passcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Branch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='Hostel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Roll_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='passcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')]),
        ),
    ]
