# Generated by Django 5.1.4 on 2025-01-30 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_lib_admin_ldap_id_remove_user_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib_admin',
            name='DOB',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
