# Generated by Django 5.1.4 on 2025-01-30 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_lib_admin_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib_admin',
            name='DOB',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
