# Generated by Django 5.1.4 on 2025-01-30 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_lib_admin_dob_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib_admin',
            name='DOB',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
