# Generated by Django 5.1.4 on 2025-01-30 15:17

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_lib_admin_dob_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='lib_admin',
            name='ldap_id',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[backend.models.validate_iitb_email]),
        ),
        migrations.AddField(
            model_name='user',
            name='ldap_id',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[backend.models.validate_iitb_email]),
        ),
    ]
