# Generated by Django 5.1.4 on 2025-01-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_lib_admin_ldap_id_user_ldap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
