# Generated by Django 5.1.4 on 2025-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lib_admin',
            name='profile_photo',
            field=models.ImageField(default='profile_photo/default-avatar-profile-icon-social-media-user-photo-in-flat-style-vector.jpg', upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile_photo/default-avatar-profile-icon-social-media-user-photo-in-flat-style-vector.jpg', upload_to='profile_photo/'),
        ),
    ]
