# Generated by Django 5.1.4 on 2025-01-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=100)),
                ('cover_page', models.ImageField(blank=True, null=True, upload_to='cover_page/')),
                ('published_year', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
    ]
