# Generated by Django 5.1.4 on 2025-01-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_available_copies_book_total_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
    ]
