# Generated by Django 5.1.4 on 2025-01-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_avg_rating_book_ratings_count_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review_text',
        ),
    ]
