# Generated by Django 5.1.4 on 2025-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_comment_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(default='cover_page/67d525a6-7901-4ee3-b0f8-3a4cf020a0de.webp', upload_to='cover_page/'),
        ),
    ]
