# Generated by Django 5.1.4 on 2025-01-28 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_comment_review_review_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='book',
            new_name='the_book',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='the_user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='the_book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='the_user',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('the_book', 'the_user')},
        ),
        migrations.AlterField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
