# Generated by Django 5.1.4 on 2025-02-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_cover_page'),
        ('books', '0006_rename_book_rating_the_book_and_more'),
    ]

    operations = [
    ]
